name: SonarCloud Test

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: Análise com SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache do Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Executar análise Sonar
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=teste \
          -Dsonar.organization=carlossfb \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
